lista_de_palavras = (
    "abacate", "abstrato", "amor", "aquarela", "autêntico", "ágil", "binário", "bola", "brilhante", "brisa", "bússola",
    "bipolar", "cachorro", "caleidoscópio", "coragem", "criptográfico", "cíclico", "cúpula", "dado", "degradê",
    "diálogo",
    "dinâmica", "dinâmico", "distópico", "eclipse", "efêmero", "elefante", "empatia", "esférico", "exótico",
    "felicidade",
    "fênix", "fictício", "foca", "fluorescente", "fragmentado", "geometria", "girafa", "gnóstico", "górgona",
    "gratidão",
    "glacial", "harmônico", "hélice", "holográfico", "hortelã", "híbrido", "icônico", "idílico", "inovação",
    "iridescente",
    "ícaro", "índigo", "jacaré", "jasmim", "jocoso", "jovial", "júbilo", "justaposto", "kafkiano", "ketchup",
    "kilobyte",
    "kinético", "kiwi", "labirinto", "lâmpada", "lateral", "lírico", "liberdade", "lúdico", "magnético", "metamorfose",
    "místico", "mórbido", "música", "macaco", "nebuloso", "néctar", "nostálgico", "natureza", "nômade", "oásis",
    "oblíquo",
    "onírico", "orgânico", "otimismo", "óculos", "paz", "pictórico", "polimorfo", "pulsar", "papagaio", "prismático",
    "quântico", "quasar", "querubim", "quimera", "quixotesco", "rapsódico", "réquiem", "respeito", "rítmico", "robusto",
    "rato", "sequencial", "sinfonia", "sinuoso", "sinceridade", "sistêmico", "sol", "sinuoso", "sequencial", "tático",
    "tatu", "teórico", "tranquilidade", "túnel", "turbulento", "uni", "uníssono", "universo", "utópico", "urso",
    "vanguarda", "vela", "vetorial", "vibrante", "volátil", "visão", "wafer", "wabi-sabi", "waifu", "waffle", "wok",
    "xadrez", "xarope", "xenofilia", "xenofobia", "xenônio", "xerófilo", "yacht", "yard", "yen", "yang", "yucca", "zen",
    "zarcão", "zebra", "zênite", "zigurate", "zircão")
